name: 自动同步上游更新

permissions: write-all

on:
  schedule:
    - cron: '30 07,15,23 * * *'
  workflow_dispatch:

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 同步上游变化
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: snailyp/text2pic
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false

      - name: 同步检查
        if: failure()
        run: |
          echo "[Error] 同步失败。可能是由于上游仓库的变更导致冲突，请尝试手动同步。"
          exit 1
